import openai
from openai import AsyncOpenAI
from src.config.settings import settings

class LLMReasoningAgent:
    """
    A reasoning agent that uses OpenAI's language models to generate biomedical hypotheses 
    regarding gene involvement in diseases.

    Attributes:
        api_key (str): The API key for accessing OpenAI services.
        model (str): The name of the model to be used for generating completions.
        prompt_instructions (str): The instructions that guide the language model's responses.
        client (AsyncOpenAI): The asynchronous OpenAI client instance.
    """

    def __init__(self):
        """Initialize the LLMReasoningAgent with API key, model, and prompt instructions."""
        self.api_key = settings.openai_api_key
        self.model = settings.model_name
        self.prompt_instructions = settings.llm_prompt_instructions
        self.client = AsyncOpenAI(api_key=self.api_key)

    async def generate_hypothesis_async(self, query: str, context: str = "") -> str:
        """
        Asynchronously generate a biomedical hypothesis based on a query and context.

        Args:
            query (str): The query string requesting a hypothesis.
            context (str, optional): Additional context to include in the prompt.

        Returns:
            str: The hypothesis generated by the language model, or an error message on failure.
        """
        prompt = f"{self.prompt_instructions}\n\nContext: {context}\n\nQuery: {query}\n\nHypothesis:"
        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": self.prompt_instructions},
                    {"role": "user", "content": f"{query}\n\nContext: {context}"}
                ],
                temperature=0.0
            )
        except openai.error.OpenAIError as e:
            return f"Error generating hypothesis: {str(e)}"
        hypothesis = response.choices[0].message.content.strip()
        return hypothesis